### PR TITLE
Completed sub-task-1,2 of Task 1

### PR DESCRIPTION
**Pull request by dhushyanth-s**
Made changes to `user-info.js` file and added new file `googlesheetsService.js` in commands directory that adds bot function to read from a specific spreadsheet shared to it and returns out the name and Roll No of the user from the spreadsheet in the chat when the user uses the command `!user-info`.

### CODE REVIEW

**Review by piyushchauhan — CHANGES_REQUESTED** [review]
It will be better if you keep the spreadsheetService.js in new /services folder. Let's not clutter the commands folder unnecessarily because each file in commands folder is being read in main.js

**Comment by piyushchauhan** [comment]
In which discord server did you test the bot? Did you not use the test server I mentioned in Readme.md?

**Comment by dhushyanth-s** [comment]
The invite to the test server mentioned in the repo expired. Thats why I had created a new private server and tested it there

**Comment by piyushchauhan** [comment]
@dhushya  https://discord.gg/BpBPWjz use this invite link

**Comment by dhushyanth-s** [comment]
I have made the necessary changes to the file structures

**Comment by dhushyanth-s** [comment]
The id of the spreadsheet can be found from its url
image
The highlighted part in the given image above is the id of the database

**Pull request merged**
