### PR TITLE
Updated user-info.js for name capitalization

### PR DESCRIPTION
**Pull request by kushal98**

### CODE REVIEW

**Review by piyushchauhan — CHANGES_REQUESTED** [review]
Make a complete function that returns the final string of real name in the desired format.
Like `let realName = convertCaseName(realName)

**Comment by kushal98** [comment]
Made the suggested change please check

**Review by piyushchauhan — APPROVED** [review]
LGTM. Fixed #10

**Comment by piyushchauhan** [comment]
Fixes #10

**Pull request merged**
